Start refactor and commit changes so far.

diff --git a/bin/mobash b/bin/mobash
--- a/bin/mobash
+++ b/bin/mobash
@@ -35,73 +35,69 @@ mo_main ()
     function mobash_config_read_file () 
     { 
         if [[ -f $1 && -r $1 ]]; then
-            mobash_config_read_BIFS=$IFS;
             unset IFS;
-            for mobash_config_read_i in $(cat $1);
+            local i j;
+            for i in $(cat $1);
             do
-                mobash_config_read_BIFS_2=$IFS;
                 IFS='=';
-                mobash_config_read_j=($mobash_config_read_i);
-                mobash_config_switch_key "${mobash_config_read_j[0]}" "${mobash_config_read_j[1]}";
-                IFS=$mobash_config_read_BIFS_2;
+                j=($i);
+                mobash_config_switch_key "${j[0]}" "${j[1]}";
             done;
-            IFS=$mobash_config_read_BIFS;
         fi
     };
     function mobash_config_switch_key () 
     { 
         case "$1" in 
             'config_path')
-                MOBASH_CONFIG_PATH="$2"
+                CONFIG_PATH="$2"
             ;;
             'source_path')
-                MOBASH_SOURCE_PATH="$2"
+                SOURCE_PATH="$2"
             ;;
             'include_path')
-                MOBASH_INCLUDE_PATH="$2"
+                INCLUDE_PATH="$2"
             ;;
             'import_path')
-                MOBASH_IMPORT_PATH="$2"
+                IMPORT_PATH="$2"
             ;;
             'bin_dir')
-                MOBASH_BIN_DIR="$2"
+                BIN_DIR="$2"
             ;;
         esac
     };
     function mobash_config_init () 
     { 
         echo -e "${YEL}Collapsing configs...$RS";
-        mobash_config_init_BIFS=$IFS;
         IFS='
 ';
-        for mobash_config_init_i in $(resolve_expanded_path $@);
+        local i;
+        for i in $(resolve_expanded_path $@);
         do
-            mobash_config_read_file "${mobash_config_init_i}/.mobashrc";
+            mobash_config_read_file "${i}/.mobashrc";
         done;
-        IFS=$mobash_config_init_BIFS;
-        print_ln "%-${FORMAT_WIDTH}s" "  MOBASH_CONFIG_PATH: " $CYN;
-        echo -e "${GRN}$MOBASH_CONFIG_PATH";
-        print_ln "%-${FORMAT_WIDTH}s" "  MOBASH_SOURCE_PATH: " $CYN;
-        echo -e "${GRN}$MOBASH_SOURCE_PATH";
-        print_ln "%-${FORMAT_WIDTH}s" "  MOBASH_INCLUDE_PATH: " $CYN;
-        echo -e "${GRN}$MOBASH_INCLUDE_PATH";
-        print_ln "%-${FORMAT_WIDTH}s" "  MOBASH_IMPORT_PATH: " $CYN;
-        echo -e "${GRN}$MOBASH_IMPORT_PATH";
-        print_ln "%-${FORMAT_WIDTH}s" "  MOBASH_BIN_DIR: " $CYN;
-        echo -e "${GRN}$MOBASH_BIN_DIR";
+        print_ln "%-${FORMAT_WIDTH}s" "  CONFIG_PATH: " $CYN;
+        echo -e "${GRN}$CONFIG_PATH";
+        print_ln "%-${FORMAT_WIDTH}s" "  SOURCE_PATH: " $CYN;
+        echo -e "${GRN}$SOURCE_PATH";
+        print_ln "%-${FORMAT_WIDTH}s" "  INCLUDE_PATH: " $CYN;
+        echo -e "${GRN}$INCLUDE_PATH";
+        print_ln "%-${FORMAT_WIDTH}s" "  IMPORT_PATH: " $CYN;
+        echo -e "${GRN}$IMPORT_PATH";
+        print_ln "%-${FORMAT_WIDTH}s" "  BIN_DIR: " $CYN;
+        echo -e "${GRN}$BIN_DIR";
         echo
     };
     function mobash_finalize () 
     { 
         echo;
         print_ln "%-${FORMAT_WIDTH}s" "Finalizing script " $YEL;
-        echo 'mo_main "$@"' >> $MOBASH_BIN_NEW;
+        echo 'mo_main "$@"' >> $BIN_NEW;
         if [[ -n $PRESERVE_TEMP_FILES ]]; then
-            cp $MOBASH_BIN_NEW $MOBASH_BIN;
+            cp $BIN_NEW $BIN;
         else
-            mv $MOBASH_BIN_NEW $MOBASH_BIN;
+            mv $BIN_NEW $BIN;
         fi;
-        chmod 755 $MOBASH_BIN;
+        chmod 755 $BIN;
         echo -e "$RS${GRN}Complete$RS";
         mobash_cleanup
     };
@@ -110,10 +106,10 @@ mo_main ()
         print_ln "%-${FORMAT_WIDTH}s" "Cleaning up files " $YEL;
         echo -e "$RS${GRN}Complete$RS";
         if [[ -z $PRESERVE_TEMP_FILES ]]; then
-            rm $MOBASH_BIN_NEW >&/dev/null;
-            rm $MOBASH_SOURCE_FILE_CUSTOM >&/dev/null;
+            rm $BIN_NEW >&/dev/null;
+            rm $SOURCE_FILE_CUSTOM >&/dev/null;
         fi;
-        exit
+        exit 0
     };
     function mobash_resolve_function_for_file () 
     { 
@@ -121,7 +117,7 @@ mo_main ()
         func=$2;
         print_ln "%-${FORMAT_WIDTH}s" "    $func(): " $MGT;
         echo -n -e "$RED";
-        bash -c 'source '$file'; if [[ $(declare -f '$func') == "" ]]; then exit 1; else declare -f '$func' | grep -v \"^$\" >> '$MOBASH_BIN_NEW'; fi';
+        bash -c 'source '$file'; if [[ $(declare -f '$func') == "" ]]; then exit 1; else declare -f '$func' | grep -v \"^$\" >> '$BIN_NEW'; fi';
         if [[ $? == 1 ]]; then
             echo -e "No valid function declaration found.$RS";
             echo;
@@ -133,19 +129,22 @@ mo_main ()
     function mobash_resolve_imports () 
     { 
         echo -e "${YEL}Building dependency list...$RS";
-        mobash_source_file_name="$1.shs";
-        declare -i MOBASH_IMPORTS_N;
-        declare -a MOBASH_IMPORTS;
-        unset MOBASH_IMPORTS_I;
-        for mobash_include_i in "${!MOBASH_INCLUDE_FILES[@]}";
+        dict_init MOBASH_IMPORTS;
+        local include;
+        unset IFS;
+        for include in $(dict_get_keys INCLUDE_FILES);
         do
-            print_ln "%-${FORMAT_WIDTH}s" "  ${MOBASH_INCLUDE_FILES[$mobash_include_i]}: " $CYN;
-            echo -e "${LGRN}${MOBASH_INCLUDE_ABSOLUTE_FILES[$mobash_include_i]}$RS";
-            for mobash_import in `grep "^#@import" "${MOBASH_INCLUDE_ABSOLUTE_FILES[$mobash_include_i]}" | awk '{ print $2 }' | sort | uniq`;
+            local absolute="$(dict_get INCLUDE_FILES $include)";
+            print_ln "%-${FORMAT_WIDTH}s" "  $include: " $CYN;
+            echo -e "${LGRN}$absolute$RS";
+            local import;
+            unset IFS;
+            for import in $(grep "^#@import" "$absolute" | awk '{ print $2 }' | sort | uniq);
             do
-                mobash_insert_import $mobash_import "${MOBASH_INCLUDE_FILES[$mobash_include_i]}";
+                mobash_insert_import "$import" "$absolute";
             done;
         done;
+        dict_dump MOBASH_IMPORTS;
         declare -a mobash_imports_searched;
         unset MOBASH_IMPORT_FILES;
         mobash_imports_needed="true";
@@ -158,8 +157,8 @@ mo_main ()
                     mobash_imports_searched[$MOBASH_IMPORTS_N]="true";
                     print_ln "%-${FORMAT_WIDTH}s" "  $mobash_import: " $CYN;
                     mobash_module=`echo -n "$mobash_import" | sed 's/\..*//'`;
-                    if [[ ! -n `mobash_get_file_map_index $mobash_module` ]]; then
-                        mobash_module_file=`resolve_file_in_path "$mobash_module.shm" "$MOBASH_IMPORT_PATH" ":"`;
+                    if [[ ! -n $(mobash_get_file_map_index $mobash_module) ]]; then
+                        mobash_module_file=$(resolve_file_in_path "$mobash_module.shm" "$IMPORT_PATH" ":");
                         if [[ ! -n $mobash_module_file ]]; then
                             echo -e "${RED}No file found in path for: $mobash_module$RS";
                             mobash_cleanup;
@@ -188,14 +187,13 @@ mo_main ()
     { 
         if [[ -n "$1" ]]; then
             print_ln "%-$(( $FORMAT_WIDTH + 2 ))s" "    $1: " $MGT;
-            mobash_insert_import_n=`mobash_get_import_index $1`;
-            if [[ -n $mobash_insert_import_n ]]; then
-                echo -e "${LYEL}${MOBASH_IMPORTS[$mobash_insert_import_n]}$RS";
+            local current="$(dict_get MOBASH_IMPORTS "$1")";
+            if [[ -n $current ]]; then
+                echo -e "${LYEL}$current$RS";
                 return 1;
             else
                 echo -e "${GRN}New dependency$RS";
-                MOBASH_IMPORTS[${#MOBASH_IMPORTS_I[@]}]="$2";
-                MOBASH_IMPORTS_I[${#MOBASH_IMPORTS_I[@]}]="$1";
+                dict_set MOBASH_IMPORTS "$1" "$2";
                 return 0;
             fi;
         fi
@@ -248,7 +246,7 @@ mo_main ()
                 for mobash_transfer_name in ${mobash_transfer_names[@]};
                 do
                     print_ln "%-$(( $FORMAT_WIDTH + 2 ))s" "    $mobash_transfer_name: " $MGT;
-                    declare -f "${mobash_transfer_current}_$mobash_transfer_name" >> $MOBASH_BIN_NEW;
+                    declare -f "${mobash_transfer_current}_$mobash_transfer_name" >> $BIN_NEW;
                     echo -e "${GRN}Complete$RS";
                 done;
             else
@@ -256,75 +254,67 @@ mo_main ()
             fi );
         fi
     };
-    function mobash_get_import_index () 
-    { 
-        for mobash_get_import_n in "${!MOBASH_IMPORTS_I[@]}";
-        do
-            if [[ "$1" == "${MOBASH_IMPORTS_I[$mobash_get_import_n]}" ]]; then
-                echo $mobash_get_import_n;
-                break;
-            fi;
-        done
-    };
     function mobash_get_filenames () 
     { 
         print_ln "%-${FORMAT_WIDTH}s" "Resolving source " $YEL;
-        MOBASH_SOURCE_FILE=`resolve_file_in_path "$1.shs" "$MOBASH_SOURCE_PATH" ":"`;
-        if [[ "$MOBASH_SOURCE_FILE" == "" ]]; then
+        SOURCE_FILE=$(resolve_file_in_path "$1.shs" "$SOURCE_PATH" ":");
+        if [[ ! -n $SOURCE_FILE ]]; then
             echo -e "${RED}No source found in path for: $1.shs$RS";
-            exit;
+            exit 1;
         fi;
-        MOBASH_SOURCE_FILE_CUSTOM="$MOBASH_SOURCE_FILE.custom";
-        echo -e "${LGRN}$MOBASH_SOURCE_FILE$RS";
+        SOURCE_FILE_CUSTOM="$SOURCE_FILE.custom";
+        echo -e "${LGRN}$SOURCE_FILE$RS";
         echo -e "${YEL}Finding includes...$RS";
-        unset MOBASH_INCLUDE_FILES;
-        unset MOBASH_INCLUDE_ABSOLUTE_FILES;
-        MOBASH_INCLUDE_FILES[0]="$1.shs";
-        MOBASH_INCLUDE_ABSOLUTE_FILES[0]="$MOBASH_SOURCE_FILE";
-        for mobash_include_file in `grep "^#@include" "$MOBASH_SOURCE_FILE" | awk '{ print $2 }'`;
+        dict_init INCLUDE_FILES;
+        dict_set INCLUDE_FILES "$1.shs" "$SOURCE_FILE";
+        local include_file include_absolute_file;
+        unset IFS;
+        for include_file in $(grep "^#@include" "$SOURCE_FILE" | awk '{ print $2 }');
         do
-            print_ln "%-${FORMAT_WIDTH}s" "  $mobash_include_file: " $CYN;
-            mobash_include_absolute_file=`resolve_file_in_path "$mobash_include_file" "$MOBASH_INCLUDE_PATH" ":"`;
-            if [[ -n "$mobash_include_absolute_file" ]]; then
-                MOBASH_INCLUDE_ABSOLUTE_FILES[${#MOBASH_INCLUDE_FILES[@]}]="$mobash_include_absolute_file";
-                MOBASH_INCLUDE_FILES[${#MOBASH_INCLUDE_FILES[@]}]="$mobash_include_file";
-                echo -e "${LGRN}$mobash_include_absolute_file$RS";
+            print_ln "%-${FORMAT_WIDTH}s" "  $include_file: " $CYN;
+            include_absolute_file=$(resolve_file_in_path "$include_file" "$INCLUDE_PATH" ":");
+            if [[ -n $include_absolute_file ]]; then
+                dict_set INCLUDE_FILES "$include_file" "$include_absolute_file";
+                echo -e "${LGRN}$include_absolute_file$RS";
             else
-                echo -e "${RED}No source file in path for: $mobash_include_file$RS";
+                echo;
+                dict_dump INCLUDE_FILES;
+                echo -e "\n${RED}No source file in path for: $include_file$RS";
                 mobash_cleanup;
             fi;
         done;
-        MOBASH_CONFIG_FILE=`cat $MOBASH_SOURCE_FILE | grep "^#@config" | head -1 | awk '{ print $2 }'`;
-        if [[ -n $MOBASH_CONFIG_FILE ]]; then
+        CONFIG_FILE=$(cat $SOURCE_FILE | grep "^#@config" | head -1 | awk '{ print $2 }');
+        if [[ -n $CONFIG_FILE ]]; then
             echo;
             print_ln "%-${FORMAT_WIDTH}s" "Resolving config " $YEL;
-            mobash_temp_config_file=`resolve_file_in_path "$MOBASH_CONFIG_FILE" "$MOBASH_CONFIG_PATH" ":"`;
-            if [[ -n $mobash_temp_config_file ]]; then
-                MOBASH_CONFIG_FILE="$mobash_temp_config_file";
-                echo -e "${LGRN}$mobash_temp_config_file$RS";
+            local temp_config_file=$(resolve_file_in_path "$CONFIG_FILE" "$CONFIG_PATH" ":");
+            if [[ -n $temp_config_file ]]; then
+                CONFIG_FILE="$temp_config_file";
+                echo -e "${LGRN}$temp_config_file$RS";
             else
-                echo -e "${RED}No config found in path for: $mobash_temp_config_file$RS";
-                exit;
+                echo -e "${RED}No config found in path for: $temp_config_file$RS";
+                exit 1;
             fi;
         fi;
         print_ln "%-${FORMAT_WIDTH}s" "Resolving output " $YEL;
-        MOBASH_BIN="`resolve_dir $MOBASH_BIN_DIR`/$1$MOBASH_BIN_EXTENSION";
-        MOBASH_BIN_NEW="$MOBASH_BIN.new";
-        echo -e "${LGRN}$MOBASH_BIN$RS"
+        BIN="$(resolve_dir $BIN_DIR)/$1$BIN_EXTENSION";
+        BIN_NEW="$BIN.new";
+        echo -e "${LGRN}$BIN$RS"
     };
     function mobash_get_custom_contents () 
     { 
         echo -e "\n${YEL}Collecting custom...$RS";
-        echo "mo_main() {" > $MOBASH_SOURCE_FILE_CUSTOM;
-        for ((mobash_include_i=${#MOBASH_INCLUDE_ABSOLUTE_FILES[@]}-1 ; mobash_include_i>=0 ; mobash_include_i-- ))
+        echo "mo_main() {" > $SOURCE_FILE_CUSTOM;
+        local i f;
+        for ((i=${#INCLUDE_ABSOLUTE_FILES[@]}-1 ; i>=0 ; i-- ))
         do
-            mobash_include_f=${MOBASH_INCLUDE_ABSOLUTE_FILES[mobash_include_i]};
-            print_ln "%-${FORMAT_WIDTH}s" "  $mobash_include_f: " $CYN;
-            cat $mobash_include_f >> $MOBASH_SOURCE_FILE_CUSTOM;
-            echo >> $MOBASH_SOURCE_FILE_CUSTOM;
+            f=${INCLUDE_ABSOLUTE_FILES[$i]};
+            print_ln "%-${FORMAT_WIDTH}s" "  $f: " $CYN;
+            cat "$f" >> $SOURCE_FILE_CUSTOM;
+            echo >> $SOURCE_FILE_CUSTOM;
             echo -e "${GRN}Complete$RS";
         done;
-        echo "}" >> $MOBASH_SOURCE_FILE_CUSTOM;
+        echo "}" >> $SOURCE_FILE_CUSTOM;
         print_ln "%-${FORMAT_WIDTH}s" "Writing custom " $YEL;
         echo -n -e "$RED";
         if mobash_apply_custom_contents; then
@@ -337,22 +327,22 @@ mo_main ()
     };
     function mobash_apply_custom_contents () 
     { 
-        ( if source $MOBASH_SOURCE_FILE_CUSTOM; then
-            declare -f mo_main >> $MOBASH_BIN_NEW;
+        ( if source $SOURCE_FILE_CUSTOM; then
+            declare -f mo_main >> $BIN_NEW;
         else
             return 1;
         fi )
     };
     function mobash_init_bin () 
     { 
-        echo "#!/bin/bash" > $MOBASH_BIN_NEW;
-        echo -e "# Compiled with MoBash v$MOBASH_VERSION\n" >> $MOBASH_BIN_NEW;
-        if [[ -n $MOBASH_CONFIG_FILE ]]; then
-            cat "$MOBASH_CONFIG_FILE" >> $MOBASH_BIN_NEW;
+        echo "#!/bin/bash" > $BIN_NEW;
+        echo -e "# Compiled with MoBash v$MOBASH_VERSION\n" >> $BIN_NEW;
+        if [[ -n $CONFIG_FILE ]]; then
+            cat "$CONFIG_FILE" >> $BIN_NEW;
         fi;
-        echo -e "\n################################################################################" >> $MOBASH_BIN_NEW;
-        echo "# GENERATED CODE" >> $MOBASH_BIN_NEW;
-        echo "################################################################################" >> $MOBASH_BIN_NEW
+        echo -e "\n################################################################################" >> $BIN_NEW;
+        echo "# GENERATED CODE" >> $BIN_NEW;
+        echo "################################################################################" >> $BIN_NEW
     };
     function mobash_usage () 
     { 
@@ -409,6 +399,18 @@ EOT
         mobash_usage;
         exit 1;
     fi;
+    local BIN;
+    local BIN_NEW;
+    local CONFIG_FILE;
+    local SOURCE_FILE;
+    local SOURCE_FILE_CUSTOM;
+    local INCLUDE_FILES INCLUDE_FILES_i;
+    local MOBASH_IMPORTS MOBASH_IMPORTS_i;
+    local BIN_DIR;
+    local IMPORT_PATH;
+    local INCLUDE_PATH;
+    local SOURCE_PATH;
+    local CONFIG_PATH;
     mobash_config_init "$0";
     mobash_get_filenames $source_name;
     mobash_init_bin;
@@ -416,6 +418,124 @@ EOT
     mobash_get_custom_contents;
     mobash_transfer_import_contents;
     mobash_finalize
+}
+arrays_dump () 
+{ 
+    echo "Dump of array '$1':";
+    local i;
+    unset IFS;
+    for i in $(arrays_get_indicies $1);
+    do
+        echo -e "Key: '$i'\t\tValue: '$(arrays_get $1 $i)'";
+    done
+}
+arrays_get () 
+{ 
+    local array="$1[${2:?$(error_do 'Array index required.')}]";
+    echo "${!array}"
+}
+arrays_get_indicies () 
+{ 
+    unset IFS;
+    eval 'echo ${!'"${1:?$(error 'Array name is required.')}"'[@]}'
+}
+arrays_index_of () 
+{ 
+    local i;
+    unset IFS;
+    for i in $(arrays_get_indicies $1);
+    do
+        local elem="$(arrays_get $1 $i)";
+        if [[ $elem == $2 ]]; then
+            echo "$i";
+            return 0;
+        fi;
+    done
+}
+arrays_init () 
+{ 
+    read -a "${1:?$(error 'Array name is required.')}" <<< ''
+}
+arrays_len () 
+{ 
+    eval 'echo ${#'"$1"'[@]}'
+}
+arrays_set () 
+{ 
+    read -r "$1[$2]" <<< "$3"
+}
+dict_dump () 
+{ 
+    local dict_di="$(dict_get_index_array $1)";
+    local dict_i;
+    unset IFS;
+    echo "Dump of dict '$1':";
+    for dict_i in $(arrays_get_indicies $1);
+    do
+        echo -e "Key: '$(arrays_get $dict_di $dict_i)'\t\tValue: '$(arrays_get $1 $dict_i)'";
+    done
+}
+dict_get () 
+{ 
+    local dict_i=$(arrays_index_of "$(dict_get_index_array $1)" "${2:?$(error 'Key is required.')}");
+    if [[ -n $dict_i ]]; then
+        echo "$(arrays_get $1 $dict_i)";
+    fi
+}
+dict_get_index_array () 
+{ 
+    local dict_i="${1:?$(error 'Dictionary name is required.')}_i";
+    : ${dict_i:?$(error_do "Dictionary index array $i does not exist.")};
+    echo $dict_i
+}
+dict_get_keys () 
+{ 
+    arrays_get $(dict_get_index_array $1) @
+}
+dict_init () 
+{ 
+    arrays_init ${1:?$(error_do 'Dictionary name is required.')};
+    arrays_init $(dict_get_index_array $1)
+}
+dict_set () 
+{ 
+    local dict_di="$(dict_get_index_array $1)";
+    local dict_i=$(arrays_index_of $dict_di "${2:?$(error 'Key is required.')}");
+    : ${dict_i:=$(arrays_len $dict_di)};
+    arrays_set $dict_di $dict_i "$2";
+    arrays_set $1 $dict_i "$3"
+}
+error_do () 
+{ 
+    local depth=${2:-0};
+    echo "($(error_file)) $(error_format $depth "${1:-error}")";
+    error_exit
+}
+error_exit () 
+{ 
+    if [[ $- != *i* ]]; then
+        exit 1;
+    fi
+}
+error_file () 
+{ 
+    echo "$(basename "${0#-}")"
+}
+error_format () 
+{ 
+    local prefix;
+    local depth=$(( $1 + 1 ));
+    local frame_depth=$(( $depth + 1 ));
+    if [[ -n ${BASH_SOURCE[$frame_depth]} ]]; then
+        prefix="at ${FUNCNAME[$depth]} (called from ${BASH_SOURCE[$frame_depth]}:${BASH_LINENO[$depth]})";
+    else
+        prefix="at $(ps -ocommand= -p $PPID | awk '{print $1}') (parent process)";
+    fi;
+    if [[ -n $2 ]]; then
+        echo "$prefix: $2";
+    else
+        echo "$prefix";
+    fi
 }
 print_ln () 
 { 
